# Taken from: https://github.com/logtalk-actions/workflows/blob/master/testing_multiple_backends.yml
# Inspired by: https://github.com/logtalk-actions/setup-logtalk
name: Testing across three Prolog backends.

on: [push]

jobs:
  test:
    runs-on: Newton
    strategy:
      fail-fast: false
      matrix:
         backend: [eclipse, swi-prolog, gnu-prolog]
    steps:
       - if: matrix.backend == 'eclipse'
         name: Install backend
         uses: logtalk-actions/setup-eclipse@master
         with:
           eclipse-version: '7.0_54'
       - if: matrix.backend == 'swi-prolog'
         name: Install backend
         uses: logtalk-actions/setup-swi-prolog@master
         with:
           swi-prolog-version: latest
      - if: matrix.backend == 'gnu-prolog'
        name: Install backend
        uses: logtalk-actions/setup-gnu-prolog@master
        with:
            gnu-prolog-version: latest
      - name: Install Logtalk
        uses: logtalk-actions/setup-logtalk@master
        with:
          logtalk-version: git
      - name: Checkout Logtalk application to be tested
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Define environment variable for the test results
        run: echo "DEPLOYMENT_STATUS=skipped" >> $GITHUB_ENV # Taken from https://github.com/JamesIves/github-pages-deploy-action/issues/500#issuecomment-728375894
      - name: Run the application tests
        run: |
          logtalk_tester -p ${{ matrix.backend }} -f xunit -c xml || EXIT=$?
          xunit-viewer --results=xunit_report.xml --output=xunit_report.html
          xsltproc --stringparam prefix work/$(basename $GITHUB_REPOSITORY)/$(basename $GITHUB_REPOSITORY)/ --stringparam url https://github.com/$GITHUB_REPOSITORY/tree/$GITHUB_SHA -o coverage_report.html coverage_report.xml
          echo "EXIT=$EXIT" >> $GITHUB_ENV
      - name: Upload xUnit report
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.backend }}-xunit-report
          path: xunit_report.html
      - name: Upload code coverage report
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.backend }}-code-coverage-report
          path: coverage_report.html
      - name: Set workflow exit status after the test results
        run: exit $EXIT
